version: '3'

services:
  api:
    build: ecommerce-api/
    depends_on:
      - 'database'
    volumes:
      - './ecommerce-api:/src/app'
      - '/src/app/node_modules'

    ports: 
      - '3001:3001'

  client:
    build: ecommerce-client/
    depends_on:
      - 'database'
      - 'api'
    volumes:
      - './ecommerce-client:/web'
      - '/web/node_modules'
    ports:
      - '3000:3000'
    stdin_open: true

  database:
    build: postgresql/
    restart: always
    environment:
      POSTGRES_USER: ecommerce
      POSTGRES_PASSWORD: password
      
